-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.employees
(
    employee_id smallint NOT NULL,
    company_name character varying(50) NOT NULL,
    company_website character varying(50) NOT NULL,
    home_phone character varying(11) NOT NULL,
    mail character varying(50) NOT NULL,
    password character varying(50) NOT NULL,
    password_repeat character varying(50) NOT NULL,
    PRIMARY KEY (employee_id)
);

CREATE TABLE public.job_positions
(
    id smallint NOT NULL,
    name character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_seekers
(
    job_seeker_id smallint NOT NULL,
    first_name character varying(10) NOT NULL,
    last_name character varying(20) NOT NULL,
    nationality_id character varying(11) NOT NULL,
    birth_date date NOT NULL,
    mail character varying(50) NOT NULL,
    password character varying(50) NOT NULL,
    password_repeat character varying(50) NOT NULL,
    PRIMARY KEY (job_seeker_id)
);

CREATE TABLE public.system_personels
(
    system_personel_id smallint NOT NULL,
    first_name character varying(10) NOT NULL,
    last_name character varying(20) NOT NULL,
    mail character varying(50) NOT NULL,
    password character varying(50) NOT NULL,
    password_repeat character varying(50) NOT NULL,
    PRIMARY KEY (system_personel_id)
);
END;